version: '2'
services:
  mysql:
    image: mysql:8.0.32
    networks:
      - wordpress
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=DhBqFJO4fIAY7YNgYKDRX33sGt0TjkO
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=kRnEryGp8OMtmQpRyhBXnfGEBaxorKP
    volumes:
      - mysql:/var/lib/mysql
  wordpress:
    image: wordpress:6.1.1
    networks:
      - wordpress
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=kRnEryGp8OMtmQpRyhBXnfGEBaxorKP
    volumes:
      - www:/var/www/html
  nginx:
    image: nginx:1.22.1
    networks:
      - wordpress
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/usr/local/nginx/cert
networks:
  wordpress:
    driver: bridge
volumes:
  mysql: {}
  www: {}
